---
name: 03-02 Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World from bash!"

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello World from python!")
        shell: python

  say-hello-imported-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d # v1.1
        with:
          who-to-greet: "World from an imported action!"
