---
name: 03-02 Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World from bash!"

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello World from python!")
        shell: python

  say-hello-imported-action:
    runs-on: ubuntu-24.04
      - uses: actions/hello-world-javascript-action@main
        with:
        who-to-greet: "World from an imported action!"
