---
name: 03-03 Workflows, Jobs, and steps

on:
  workflow_dispatch:

jobs:
  job-01:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "A job"
      - run: echo "with one or more steps"
      - run: echo "which run sequentialy"
      - run: echo "within the same compute env"

  job-02:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Multiple jobs can run in parallel"

  job-03:
    runs-on: ubuntu-24.04
    needs:
      - job-01
      - job-02
    steps:
      - run: echo "They can also depend on one another"

  job-04:
    runs-on: ubuntu-24.04
    needs:
      - job-02
      - job-03
    steps:
      - run: echo "to form a directed ACYCLIC graph (DAG)"