---
name: 06-01 Composite Action Demo
on:
  workflow_dispatch:

jobs:
  hello-world-1:
    runs-on: ubuntu-24.04
    name: One usage of the composite action
    steps:
      - uses: actions/checkout@v6
      
      - id: composite-action-instance
        uses: ./.github/actions/06-composite-action
        with:
          who-to-greet: "from composite action in hello-world-1!"

      - env:
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.random-number }}
        shell: bash
        run: echo random-number "$RANDOM_NUMBER"

  hello-world-2:
    runs-on: ubuntu-24.04
    name: Another usage of the composite action
    steps:
      - uses: actions/checkout@v6
      
      - id: composite-action-instance
        uses: ./.github/actions/06-composite-action
        with:
          who-to-greet: "from composite action in hello-world-2!"

      - env:
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.random-number }}
        shell: bash
        run: echo random-number "$RANDOM_NUMBER"